### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by Shivkumar-ssh** [Shivkumar-ssh/MS#1]
This issue is to describe the action timeline

**Comment by Shivkumar-ssh** [comment]
**09/10**
- Transcripts and documents
- CV update

**Comment by Shivkumar-ssh** [comment]
**09/11**
- Linkedin profile update
- Kickstarted my school search better, will upload the Excel here as an edit by the EOD.
[MSBA_Univ](https://github.com/Shivkumar-ssh/MS/files/7148451/MSBA_Univ.xlsx)
- LOR preparation for Surya and JPK

**Comment by Shivkumar-ssh** [comment]
**09/12**
- My friends push me. Sacrifices and dedication are key. Somu, Sharan, Bhatta, Shetty, Kulk, Ketan, Pai, Kanbo
- It's go time _right now_
- Keep thinking about it, when wonder around, plan Djokovic (demands mental strength), lost his finals to Medvedev US Open

**Comment by Shivkumar-ssh** [comment]
**09/13**
- Sushya message on Linkedin on pushing, Pushing myself.
- Visiting school websites for getting the list ready for application
- Transcripts and Documents are the only things completely ready right now.
- MS Schools to visit
 -- Purdue Lafayette
 -- SUNY Buffalo
 -- U Washington, Seattle
 -- U Wisconsin Madisson

Will add in the updated MSBA list in the next comment

**Comment by Shivkumar-ssh** [comment]
**09/14**
- Booked my GRE for 09/19
- Possibly, there will not be much activity here apart from the college search and GRE prep. Please switch tabs to [GRE](https://github.com/Shivkumar-ssh/GRE)
- Just to keep the tentative deadlines clear,
- [x] 09/19 GRE
- [x] 09/20 SOP_Draft_2
- [x] 09/26 TOEFL
- [x] 09/30 Schools 7 decide
- [x] 10/01 LOR
- [x] 10/02 SOP_Draft_3 readiness to send to Sushya, Sasi, Sai
- [x] 10/05 CV Update with clarity on projects (Work) and reduce college- focus on business projects

**Comment by Shivkumar-ssh** [comment]
**09/23**
Apologies for the delay.
The dates for TOEFL is postponed and also the SOP_Draft_2.
Dates coming up.
- [x] Book TOEFL
- [x] Read SOP references
- [x] TOEFL go through the videos
- [x] Set agenda for 09/24
- [x] Complete Star Awards thing

**Comment by Shivkumar-ssh** [comment]
**09/24**
Booked TOEFL for 10/03.
Need to speed up my application process now for Business Analytics.
1. SOP as the priority
2. TOEFL preparation

**Comment by Shivkumar-ssh** [comment]
**09/26**
- [x] Tried to develop Mark's statements from the previous day's webinar. Nonetheless, I will try to develop the  habit of self-consciousness, soon.
- [x] TOEFL ETS Official guide downloaded, Princeton also in-place. 
- [x] 09/27 Writing- practice Integrated and Independent formatting from ETS and Princeton.
- [x] Speaking sections options and format, from the official ETS. 
- [x] Give one practice test.
- [x] Reading tricks to start off with from ETS, again.
- [ ] Visualize the day for your comfort.
- [x] 09/28 Wake up by 7:20
- [x] We are going good with the SOP, just need to fasten the process and submit them to my boiz by 10/04
